# Staging overlay Docker Compose
version: "3.7" 

services:
  shibpostgres:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-staging-shibpostgres:latest

  nginx-shib:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-staging-nginx-shib:latest
    build:
      args:
        ENVIRONMENT: staging

  uclapi:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-staging-uclapi:latest
    build:
      args:
        ENVIRONMENT: staging
