# Staging overlay Docker Compose
version: "3.7" 

services:
  shibpostgres:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-prod-shibpostgres:latest

  nginx-shib:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-prod-nginx-shib:latest
    build:
      args:
        ENVIRONMENT: prod

  uclapi:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-prod-uclapi:latest
    build:
      args:
        ENVIRONMENT: prod
